// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnhxjrlqjmffpxxczkhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaHhqcmxxam1mZnB4eGN6a2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODE2MTYsImV4cCI6MjA2Mjc1NzYxNn0.sNK4lei-ozPGhBJ4SBNU7fwLh_eJZKCoZsV7Ou3Xp0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);